### ISSUE TITLE
Building fails with "error:0308010C:digital envelope routines::unsupported"

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-wallet-ext#304]
Trying to build the current latest `master` branch with Node.js 16.18.1 and yarn 1.22.19 errors with:

```
$ yarn buildProd
yarn run v1.22.19
warning ../../package.json: No license field
$ webpack --mode production
argv.mode production
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/tadej/Oasis/oasis-wallet-ext/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/tadej/Oasis/oasis-wallet-ext/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/tadej/Oasis/oasis-wallet-ext/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/tadej/Oasis/oasis-wallet-ext/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/tadej/Oasis/oasis-wallet-ext/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/tadej/Oasis/oasis-wallet-ext/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/tadej/Oasis/oasis-wallet-ext/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/tadej/Oasis/oasis-wallet-ext/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/tadej/Oasis/oasis-wallet-ext/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/tadej/Oasis/oasis-wallet-ext/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/tadej/Oasis/oasis-wallet-ext/node_modules/babel-loader/lib/index.js:59:71
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by lukaw3d** [comment]
We need to upgrade our build tooling. I think `export NODE_OPTIONS=--openssl-legacy-provider` works as a workaround
